version: "3.9"

services:
  app:
    image: ai-teddy-app:prod
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-150}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.7}
      - WHISPER_MODEL=${WHISPER_MODEL:-medium}
      - CORS_ALLOWED_ORIGINS=["https://ai-tiddy-bear-v-xuqy.onrender.com"]
      - ALLOWED_HOSTS=["ai-tiddy-bear-v-xuqy.onrender.com"]
      - PARENT_NOTIFICATION_EMAIL=jaafarhabash@yahoo.com
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=${WORKERS:-2}
      - INSTANCE_ID={{.Task.Slot}}
      - AFFINITY_COOKIE_NAME=teddy_affinity
      - AFFINITY_COOKIE_TTL_SECONDS=3600
      - OPENAI_API_KEY_FILE=/run/secrets/ai_teddy_bear_openai_api_key
      - OPENAI_STT_API_KEY_FILE=/run/secrets/ai_teddy_bear_openai_stt_api_key
      - ALLOW_AI_FAILURE_FALLBACK=false
      - ALLOW_WS_MOCK=false
    secrets:
      - ai_teddy_bear_database_url
      - ai_teddy_bear_redis_url
      - ai_teddy_bear_jwt_secret_key
      - ai_teddy_bear_secret_key
      - ai_teddy_bear_coppa_encryption_key
      - ai_teddy_bear_openai_api_key
      - ai_teddy_bear_openai_stt_api_key
      - ai_teddy_bear_elevenlabs_api_key
      - ai_teddy_bear_stripe_api_key
      - ai_teddy_bear_stripe_publishable_key
      - ai_teddy_bear_stripe_webhook_secret
      - ai_teddy_bear_sentry_dsn

secrets:
  ai_teddy_bear_database_url:
    external: true
  ai_teddy_bear_redis_url:
    external: true
  ai_teddy_bear_jwt_secret_key:
    external: true
  ai_teddy_bear_secret_key:
    external: true
  ai_teddy_bear_coppa_encryption_key:
    external: true
  ai_teddy_bear_openai_api_key:
    external: true
  ai_teddy_bear_openai_stt_api_key:
    external: true
  ai_teddy_bear_elevenlabs_api_key:
    external: true
  ai_teddy_bear_stripe_api_key:
    external: true
  ai_teddy_bear_stripe_publishable_key:
    external: true
  ai_teddy_bear_stripe_webhook_secret:
    external: true
  ai_teddy_bear_sentry_dsn:
    external: true





