apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-teddy-bear-logs-pvc
  namespace: ai-teddy-bear
  labels:
    app.kubernetes.io/name: ai-teddy-bear
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: storage
    storage.type: logs
    # Child safety compliance
    coppa.compliant: "true"
    child.safety.validated: "true"
  annotations:
    # Storage annotations
    volume.beta.kubernetes.io/storage-class: "gp3-encrypted"
    volume.kubernetes.io/storage-provisioner: "ebs.csi.aws.com"
    # Child safety annotations
    child-safety.compliance/coppa: "enabled"
    child-safety.data-retention: "90-days"
    security.encryption/enabled: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-encrypted
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-teddy-bear-data-pvc
  namespace: ai-teddy-bear
  labels:
    app.kubernetes.io/name: ai-teddy-bear
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: storage
    storage.type: data
    # Child safety compliance
    coppa.compliant: "true"
    child.safety.validated: "true"
  annotations:
    # Storage annotations
    volume.beta.kubernetes.io/storage-class: "gp3-encrypted"
    volume.kubernetes.io/storage-provisioner: "ebs.csi.aws.com"
    # Child safety annotations
    child-safety.compliance/coppa: "enabled"
    child-safety.data-retention: "90-days"
    security.encryption/enabled: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-encrypted
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-teddy-bear-secure-pvc
  namespace: ai-teddy-bear
  labels:
    app.kubernetes.io/name: ai-teddy-bear
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: storage
    storage.type: secure
    # Child safety compliance
    coppa.compliant: "true"
    child.safety.validated: "true"
  annotations:
    # Storage annotations for highly secure data
    volume.beta.kubernetes.io/storage-class: "gp3-encrypted-high-iops"
    volume.kubernetes.io/storage-provisioner: "ebs.csi.aws.com"
    # Child safety annotations
    child-safety.compliance/coppa: "enabled"
    child-safety.data-retention: "90-days"
    child-safety.encryption/aes-256: "enabled"
    security.encryption/enabled: "true"
    security.access/restricted: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-encrypted-high-iops
---
# Storage Class for encrypted volumes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-encrypted
  labels:
    app.kubernetes.io/name: ai-teddy-bear
    coppa.compliant: "true"
    child.safety.validated: "true"
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    # Child safety annotations
    child-safety.compliance/coppa: "enabled"
    security.encryption/enabled: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  encrypted: "true"
  # Use customer-managed KMS key for enhanced security
  kmsKeyId: "arn:aws:kms:us-west-2:ACCOUNT:key/KEY-ID"
reclaimPolicy: Retain
---
# High IOPS storage class for secure data
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-encrypted-high-iops
  labels:
    app.kubernetes.io/name: ai-teddy-bear
    coppa.compliant: "true"
    child.safety.validated: "true"
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    # Child safety annotations
    child-safety.compliance/coppa: "enabled"
    security.encryption/enabled: "true"
    security.access/restricted: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
  iops: "16000"
  throughput: "1000"
  encrypted: "true"
  # Use customer-managed KMS key for enhanced security
  kmsKeyId: "arn:aws:kms:us-west-2:ACCOUNT:key/KEY-ID"
reclaimPolicy: Retain