apiVersion: v1
kind: Secret
metadata:
  name: ai-teddy-bear-secrets
  namespace: ai-teddy-bear
  labels:
    app.kubernetes.io/name: ai-teddy-bear
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: secrets
  annotations:
    # Security annotations
    security.policy/encryption: "aes-256"
    child-safety.compliance/coppa: "compliant"
    data.classification: "confidential"
type: Opaque
stringData:
  # Application secrets (these should be populated from external secret management)
  SECRET_KEY: "REPLACE_WITH_ACTUAL_SECRET"
  JWT_SECRET_KEY: "REPLACE_WITH_ACTUAL_JWT_SECRET"
  COPPA_ENCRYPTION_KEY: "REPLACE_WITH_ACTUAL_COPPA_KEY"
  
  # Database credentials
  DB_PASSWORD: "REPLACE_WITH_DB_PASSWORD"
  REDIS_PASSWORD: "REPLACE_WITH_REDIS_PASSWORD"
  
  # External API keys
  OPENAI_API_KEY: "REPLACE_WITH_OPENAI_KEY"
  ELEVENLABS_API_KEY: "REPLACE_WITH_ELEVENLABS_KEY"
  SENTRY_DSN: "REPLACE_WITH_SENTRY_DSN"
  
  # Email configuration
  PARENT_NOTIFICATION_EMAIL: "REPLACE_WITH_EMAIL"
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-teddy-bear-tls
  namespace: ai-teddy-bear
  labels:
    app.kubernetes.io/name: ai-teddy-bear
    app.kubernetes.io/component: tls-certificate
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTi... # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTi... # Base64 encoded private key
---
# External Secrets Operator configuration for secure secret management
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ai-teddy-bear-secret-store
  namespace: ai-teddy-bear
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-teddy-bear-secrets-external
  namespace: ai-teddy-bear
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: ai-teddy-bear-secret-store
    kind: SecretStore
  target:
    name: ai-teddy-bear-secrets-managed
    creationPolicy: Owner
  data:
  - secretKey: SECRET_KEY
    remoteRef:
      key: ai-teddy-bear/production
      property: secret_key
  - secretKey: JWT_SECRET_KEY
    remoteRef:
      key: ai-teddy-bear/production
      property: jwt_secret_key
  - secretKey: COPPA_ENCRYPTION_KEY
    remoteRef:
      key: ai-teddy-bear/production
      property: coppa_encryption_key
  - secretKey: DB_PASSWORD
    remoteRef:
      key: ai-teddy-bear/production
      property: db_password
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: ai-teddy-bear/production
      property: redis_password
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: ai-teddy-bear/production
      property: openai_api_key
  - secretKey: ELEVENLABS_API_KEY
    remoteRef:
      key: ai-teddy-bear/production
      property: elevenlabs_api_key
  - secretKey: SENTRY_DSN
    remoteRef:
      key: ai-teddy-bear/production
      property: sentry_dsn