name: Router Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-routers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi
          pip install -r requirements.txt || true

      - name: Run APIRouter validation script
        run: |
          python scripts/check_routers.py
